sparkConf:
  eventLog:
    enabled: false
    dir: file:///usr/local/hadoop-3.3.3/spark-3.3.0-bin-without-hadoop/localHistory
  history:
    fs:
      logDirectory: file:///usr/local/hadoop-3.3.3/spark-3.3.0-bin-without-hadoop/localHistory
  driver:
    memory: 2g
    extraJavaOptions: -Dspring.profiles.active=default
  submit:
    deployMode: client

submitConf:
  args: jobBeanName:app
  master: local[*]
  jarPath: /Users/Ian_Rakhmatullin/IdeaProjects/sparkAlchemy/sparkApp/build/libs/sparkApp-1.0-SNAPSHOT-all.jar
