sparkConf:
  eventLog:
    enabled: true
    dir: file:///usr/local/hadoop-3.2.2/spark-3.1.1-bin-without-hadoop/history
  history:
    fs:
      logDirectory: file:///usr/local/hadoop-3.2.2/spark-3.1.1-bin-without-hadoop/history
  driver:
    memory: 2g
    extraJavaOptions: -Dspring.profiles.active=default
  submit:
    deployMode: client

submitConf:
  args: jobBeanName:app
  master: local[*]
  jarPath: /Users/Ian_Rakhmatullin/IdeaProjects/sparkAlchemy/sparkApp/build/libs/sparkApp-1.0-SNAPSHOT-all.jar
